resources:
- name: git_monitor
  type: git
  tags: [public]
  source:
    uri: git@github.com:lee-andrew/ubuntu_temp_monitor.git
    branch: master
    private_key: ((private_key))

- name: 5m
  type: time
  tags: [public]
  source: {interval: 5m}

jobs:
- name: temp_monitor
  plan:
  - get: 5m
    tags: [public]
    trigger: true
  - get: git_monitor
    tags: [public]
  - task: read_temp
    tags: [public]
    params:
      ssh_user: ((ssh_user))
      ssh_pass: ((ssh_pass))
      ssh_host: ((ssh_host))
    file: git_monitor/tasks/get_status/task.yml
    
  - task: git_state
    tags: [public]
    params:
      git_user: ((git_user))
      git_email: ((git_email))
      cpu_temp_threshold: 40
      gpu_temp_threshold: 50
      psu_temp_threshold: 50
      sys_temp_threshold: 40
      cpu_fan_threshold: 1000
      case_fan1_threshold: 1000
      case_fan2_threshold: 1000
    file: git_monitor/tasks/status_threshold/task.yml
    
  - put: git_monitor
    tags: [public]
    params: {repository: output}      