platform: linux
inputs: [ {name: git_monitor}, {name: states} ]
outputs: [ {name: output} ]
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/git-ssh
run:
  path: git_monitor/tasks/status_threshold/task.sh