platform: linux
outputs: [ {name: states} ]
image_resource:
  type: docker-image
  source:
    repository: alexedev/ubuntu-sshpass
inputs: [ {name: git_monitor} ]
run: 
  path: git_monitor/tasks/get_status/task.sh
